/*ESSA BASE FOI DESENVOLVIDA PELO ALVES COM FOCO EM PERFORMANCE E OTIMIZAÇÃO.
© COPYRIGHT BY ALVES
BASE PÚBLICA - O USO E A MODIFICAÇÃO SÃO PERMITIDOS,
PORÉM É EXPRESSAMENTE PROIBIDA A VENDA OU COMERCIALIZAÇÃO
DESTA BASE, NO TODO OU EM PARTE.
NÃO VENDA, REVENDA OU COMERCIALIZE ESTA BASE
SEM A AUTORIZAÇÃO DO AUTOR.*/

import * as linguagem from './menus.js';
import mess from "./global.js";

export { linguagem, mess };
export default { linguagem, mess };
