import { tag } from "./dragonFun/_utils.js";
const TRAITS=[
"personalidade","linda","lindo","gay","hetero","lesbica","puta","gado","feio","corno","vesgo","bebado","gostoso","gostosa","golpista","nazista","otaku","pobre","rico","burro","burra","inteligente","fiel","infiel","safado","safada","ladrao","ladra","sortudo","sortuda","azarado","azarada","forte","fraco","fraca","pegador","pegadora","otario","otaria","bobo","boba","nerd","preguicoso","preguicosa","trabalhador","trabalhadora","brabo","braba","malandro","malandra","simpatico","simpatica","engracado","engracada","charmoso","charmosa","ciumento","ciumenta","romantico","romantica","responsavel","irresponsavel","introvertido","introvertida","extrovertido","extrovertida","criativo","criativa","gamer","programador","programadora","visionario","visionaria","sonhador","sonhadora","viajante","caseiro","caseira","misterioso","misteriosa","zueiro","zueira","chance","sorte"
];
const RANKS=TRAITS.map(x=>`rank${x}`);
const modules = [
  import("./dragonFun/beijo.js"),  import("./dragonFun/abraco.js"),  import("./dragonFun/carinho.js"),  import("./dragonFun/cafune.js"),  import("./dragonFun/tapa.js"),  import("./dragonFun/chute.js"),  import("./dragonFun/morder.js"),  import("./dragonFun/socar.js"),  import("./dragonFun/lamber.js"),  import("./dragonFun/matar.js"),  import("./dragonFun/comer.js"),  import("./dragonFun/gozar.js"),  import("./dragonFun/mamada.js"),  import("./dragonFun/louca.js"),  import("./dragonFun/chorao.js"),  import("./dragonFun/julgar.js"),
  import("./dragonFun/personalidade.js"),  import("./dragonFun/linda.js"),  import("./dragonFun/lindo.js"),  import("./dragonFun/gay.js"),  import("./dragonFun/hetero.js"),  import("./dragonFun/lesbica.js"),  import("./dragonFun/puta.js"),  import("./dragonFun/gado.js"),  import("./dragonFun/feio.js"),  import("./dragonFun/corno.js"),  import("./dragonFun/vesgo.js"),  import("./dragonFun/bebado.js"),  import("./dragonFun/gostoso.js"),  import("./dragonFun/gostosa.js"),  import("./dragonFun/golpista.js"),  import("./dragonFun/nazista.js"),  import("./dragonFun/otaku.js"),  import("./dragonFun/pobre.js"),  import("./dragonFun/rico.js"),  import("./dragonFun/burro.js"),  import("./dragonFun/burra.js"),  import("./dragonFun/inteligente.js"),  import("./dragonFun/fiel.js"),  import("./dragonFun/infiel.js"),  import("./dragonFun/safado.js"),  import("./dragonFun/safada.js"),  import("./dragonFun/ladrao.js"),  import("./dragonFun/ladra.js"),  import("./dragonFun/sortudo.js"),  import("./dragonFun/sortuda.js"),  import("./dragonFun/azarado.js"),  import("./dragonFun/azarada.js"),  import("./dragonFun/forte.js"),  import("./dragonFun/fraco.js"),  import("./dragonFun/fraca.js"),  import("./dragonFun/pegador.js"),  import("./dragonFun/pegadora.js"),  import("./dragonFun/otario.js"),  import("./dragonFun/otaria.js"),  import("./dragonFun/bobo.js"),  import("./dragonFun/boba.js"),  import("./dragonFun/nerd.js"),  import("./dragonFun/preguicoso.js"),  import("./dragonFun/preguicosa.js"),  import("./dragonFun/trabalhador.js"),  import("./dragonFun/trabalhadora.js"),  import("./dragonFun/brabo.js"),  import("./dragonFun/braba.js"),  import("./dragonFun/malandro.js"),  import("./dragonFun/malandra.js"),  import("./dragonFun/simpatico.js"),  import("./dragonFun/simpatica.js"),  import("./dragonFun/engracado.js"),  import("./dragonFun/engracada.js"),  import("./dragonFun/charmoso.js"),  import("./dragonFun/charmosa.js"),  import("./dragonFun/ciumento.js"),  import("./dragonFun/ciumenta.js"),  import("./dragonFun/romantico.js"),  import("./dragonFun/romantica.js"),  import("./dragonFun/responsavel.js"),  import("./dragonFun/irresponsavel.js"),  import("./dragonFun/introvertido.js"),  import("./dragonFun/introvertida.js"),  import("./dragonFun/extrovertido.js"),  import("./dragonFun/extrovertida.js"),  import("./dragonFun/criativo.js"),  import("./dragonFun/criativa.js"),  import("./dragonFun/gamer.js"),  import("./dragonFun/programador.js"),  import("./dragonFun/programadora.js"),  import("./dragonFun/visionario.js"),  import("./dragonFun/visionaria.js"),  import("./dragonFun/sonhador.js"),  import("./dragonFun/sonhadora.js"),  import("./dragonFun/viajante.js"),  import("./dragonFun/caseiro.js"),  import("./dragonFun/caseira.js"),  import("./dragonFun/misterioso.js"),  import("./dragonFun/misteriosa.js"),  import("./dragonFun/zueiro.js"),  import("./dragonFun/zueira.js"),  import("./dragonFun/chance.js"),  import("./dragonFun/sorte.js"),
  import("./dragonFun/legacy.js")
];
const loaded=await Promise.all(modules);
const handlers=new Map();
for(const mod of loaded)for(const alias of (mod.aliases||[]))handlers.set(String(alias).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase(),mod.default);
export const dragonFunAliases=[...new Set([...handlers.keys(),...RANKS])];
export default {name:"dragonfun",aliases:dragonFunAliases,category:"diversao",description:"Dragon Fun modular.",usage:"menubn",permission:"Membro",async execute(ctx){
 const n=String(ctx.command||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
 if(RANKS.includes(n)){const trait=n.slice(4);const jids=[...new Set((ctx.groupMembers||[]).map(x=>x.id||x.jid).filter(Boolean))];for(let i=jids.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[jids[i],jids[j]]=[jids[j],jids[i]];}const rows=jids.slice(0,10).map(jid=>({jid,score:Math.floor(Math.random()*101)})).sort((a,b)=>b.score-a.score);return ctx.conn.sendMessage(ctx.from,{text:`🏆 *RANK ${trait.toUpperCase()}*\n\n`+rows.map((x,i)=>`${i+1}. ${tag(x.jid)} — *${x.score}%*`).join("\n")+`\n\n🎲 Pessoas e porcentagens são sorteadas novamente a cada uso.`,mentions:rows.map(x=>x.jid)},{quoted:ctx.info});}
 const fn=handlers.get(n);if(fn)return fn(ctx);return ctx.reply("🐉 Comando Dragon Fun não encontrado.");
}};
