import { mediaFor, startForca, guessForca, startAnagram, answerSimple, startQuiz, startEnigma, startWordle, guessWordle, randomTruth, randomDare, randomNever, gamble, proposeMarriage, acceptMarriage, marriageOf, divorce, familyAction, getFamily, simpleRpgAction } from "../../../lib/features/social/dragonFunV09.js";
import { buildFunMenu } from "../../../lib/ui/menuTheme.js";
import { targetOf, tag, sendMedia, displayJid } from "./_utils.js";
function stablePercent(a,b){let h=0;for(const c of String(a)+String(b))h=(h*31+c.charCodeAt(0))>>>0;return h%101;}
export const aliases=["menubn","menujogos","menudiversao","menubrincadeiras","brincadeira","games","forca","fc","anagrama","quiz","trivia","enigma","wordle","palavra","ppt","pedrapapeltesoura","coinflip","moeda","dados","dice","cassino","slots","slotmachine","roleta","roulette","verdade","desafio","eununca","vord","jogodavelha","tictactoe","connect4","uno","stop","adedonha","cacapalavras","batalhanaval","dueloquiz","duelo","jogov","resetv","gartic","revelar_gartic","quiz_animais","revelar_animal","revelar_enigma","revelar_anagrama","participar","start_vord","help_vord","regras_vord","status_vord","rm_vord","add_vord","exit_vord","pular","reset_vord","responder","confirmar","pontos","checkpts","rankpts","sn","shipo","casal","cantada","piada","fato","conselho","elogio","reflexao","motivacional","quando","amongus","roletaban"].concat(["casar","aceitarcasamento","aceitarpedido","divorciar","minhadupla","relacionamento","casais","familia","adotaruser","adotarfilho","deserdar","arvore","criar_familia","sair_familia","deletar_familia"]);
export default async function run(ctx){
 const c=String(ctx.command||"").toLowerCase();const n=c.normalize("NFD").replace(/[\u0300-\u036f]/g,"");const target=targetOf(ctx)||ctx.sender;
 const displaySender=await displayJid(ctx,ctx.sender);const displayTarget=await displayJid(ctx,target);
 if(["dragonfun","menubn","menujogos","menudiversao","menubrincadeiras","brincadeira","games"].includes(n))return ctx.reply(buildFunMenu(ctx.prefix));

  if(n==="forca"||n==="fc"){if(ctx.args?.length){const r=guessForca(ctx.from,ctx.sender,ctx.args.join(" "));if(r.win)return ctx.reply(`🎉 Acertou! A palavra era *${r.word}*. +60 coins.`);if(r.lose)return ctx.reply(`💀 Fim de jogo! A palavra era *${r.word}*.`);if(r.ok)return ctx.reply(`🪢 ${r.masked}\n❤️ Tentativas: ${r.tries}\n💡 ${r.hint}`);}const s=startForca(ctx.from,ctx.sender);const mask=[...s.word].map(x=>x===" "?" ":"_ ").join("");return ctx.reply(`🪢 *FORCA*\n\n${mask}\n💡 Dica: ${s.hint}\n📚 Tema: ${s.theme}\n\nResponda com *${ctx.prefix}forca letra/palavra*`);}
  if(n==="anagrama"){if(ctx.args?.length){const r=answerSimple(ctx.from,ctx.sender,ctx.args.join(" "));return r.correct?ctx.reply(`✅ Acertou! *${r.answer}* +50 coins.`):ctx.reply("❌ Ainda não. Tente novamente!");}const s=startAnagram(ctx.from,ctx.sender);return ctx.reply(`🔀 *ANAGRAMA*\n\n🔤 *${s.scrambled.toUpperCase()}*\n💡 ${s.hint}\n\nResponda: *${ctx.prefix}anagrama resposta*`);}
  if(["quiz","trivia"].includes(n)){if(ctx.args?.length){const r=answerSimple(ctx.from,ctx.sender,ctx.args.join(" "));return r.correct?ctx.reply(`✅ Resposta certa: *${r.answer}*. +50 coins.`):ctx.reply("❌ Resposta incorreta. Tente de novo!");}const s=startQuiz(ctx.from,ctx.sender);return ctx.reply(`🧠 *QUIZ • ${s.category.toUpperCase()}*\n\n${s.question}\n\nResponda: *${ctx.prefix}quiz resposta*`);}
  if(n==="enigma"){if(ctx.args?.length){const r=answerSimple(ctx.from,ctx.sender,ctx.args.join(" "));return r.correct?ctx.reply(`🧩 Acertou: *${r.answer}*! +50 coins.`):ctx.reply("❌ Não foi dessa vez.");}const s=startEnigma(ctx.from,ctx.sender);return sendMedia(ctx,mediaFor("enigma"),`🧩 *ENIGMA*\n\n${s.question}\n\nResponda: *${ctx.prefix}enigma resposta*`);}
  if(["wordle","palavra"].includes(n)){if(ctx.args?.length){const r=guessWordle(ctx.from,ctx.sender,ctx.args[0]);if(r.invalid)return ctx.reply(`A palavra possui *${r.len} letras*.`);if(r.win)return ctx.reply(`🟩🟩🟩 Vitória! *${r.word}* +70 coins.`);if(r.lose)return ctx.reply(`${r.grid}\n💀 Acabaram as tentativas. Palavra: *${r.word}*`);return ctx.reply(`${r.grid}\n❤️ Restam ${r.tries} tentativa(s).`);}const s=startWordle(ctx.from,ctx.sender);return ctx.reply(`🟩 *WORDLE*\nA palavra tem *${s.word.length} letras*.\nVocê tem 6 tentativas.\n\nUse *${ctx.prefix}wordle palavra*`);}
  if(["verdade","vord"].includes(n))return ctx.reply(`💬 *VERDADE*\n${randomTruth()}`);
  if(n==="desafio")return ctx.reply(`🔥 *DESAFIO*\n${randomDare()}`);
  if(n==="eununca")return ctx.reply(`🙈 *EU NUNCA*\n${randomNever()}`);
  if(["cantada","piada","fato","conselho","elogio","reflexao","motivacional","quando"].includes(n)){const bank={cantada:["Você não é Wi-Fi, mas senti uma conexão aqui 😏","Você é estrela? Porque iluminou o grupo inteiro ✨"],piada:["Por que o computador foi ao médico? Porque pegou um vírus. 💻😂","O zero disse pro oito: belo cinto! 😭"],fato:["🐙 Polvos têm três corações.","🌌 A luz do Sol leva cerca de 8 minutos para chegar à Terra."],conselho:["🌱 Faça primeiro o que depende de você; o resto fica mais fácil de organizar.","🧭 Nem toda pressa é progresso. Escolha uma direção antes de acelerar."],elogio:["✨ Você parece ser o tipo de pessoa que melhora o clima do grupo.","🌸 Seu bom humor merece XP extra hoje."],reflexao:["🌙 Às vezes mudar de rota é parte do caminho, não um fracasso.","🐉 Consistência pequena costuma vencer motivação gigante e rara."],motivacional:["🔥 Um passo hoje ainda é um passo.","🐉 Continue acumulando XP; chefão nenhum cai no primeiro hit."],quando:["🔮 Meu palpite totalmente científico: em breve.","⏳ Os dragões disseram: ainda não, mas tá chegando."]};return ctx.reply(bank[n][Math.floor(Math.random()*bank[n].length)]);}
  if(["ppt","pedrapapeltesoura"].includes(n)){const choices=["pedra","papel","tesoura"],me=String(ctx.args?.[0]||"").toLowerCase(),bot=choices[Math.floor(Math.random()*3)];if(!choices.includes(me))return ctx.reply(`🎮 *PEDRA, PAPEL OU TESOURA*\n\n💡 *Como jogar:*\n• Escolha sua jogada após o comando\n• ${ctx.prefix}ppt pedra\n• ${ctx.prefix}ppt papel\n• ${ctx.prefix}ppt tesoura\n\n🐉 Vamos ver quem ganha!`);const win=(me==="pedra"&&bot==="tesoura")||(me==="papel"&&bot==="pedra")||(me==="tesoura"&&bot==="papel");return ctx.reply(`╭━━〔 ✊✋✌️ *PPT DRAGON* 〕━━╮\n┃ 👤 Você: *${me}*\n┃ 🐉 Kobayashi: *${bot}*\n╰━━━━━━━━━━━━━━━━━━━━╯\n\n${me===bot?"🤝 *Empate!*":win?"🏆 *Você venceu!*":"🐉 *Kobayashi venceu!*"}`);}
  if(["dados","dice","coinflip","moeda","cassino","slots","slotmachine","roleta","roulette"].includes(n)){let game="slots",choice="",bet=10;if(["dados","dice"].includes(n)){game="dice";bet=ctx.args?.[0];}else if(["coinflip","moeda"].includes(n)){game="coinflip";choice=ctx.args?.[0];bet=ctx.args?.[1];}else if(["roleta","roulette"].includes(n)){game="roulette";choice=ctx.args?.[0];bet=ctx.args?.[1];}else bet=ctx.args?.[0];const r=gamble(ctx.sender,game,bet,choice);if(!r.ok)return ctx.reply("💸 Saldo insuficiente ou aposta inválida.");return ctx.reply(`🎰 *${game.toUpperCase()}*\n${r.result}\n\n${r.win?`🏆 Ganhou *${r.prize}* coins!`:`💥 Perdeu *${r.bet}* coins.`}\n💰 Saldo: ${r.u.coins}`);}
  if(["jogodavelha","tictactoe","connect4","uno","stop","adedonha","cacapalavras","batalhanaval","dueloquiz","duelo","jogov","gartic","quiz_animais","amongus","roletaban"].includes(n)){const r=simpleRpgAction(ctx.sender,n,ctx.args?.join(" "));return ctx.reply(`🎮 *${n.toUpperCase()}*\n${r.text}\n⭐ Lv.${r.u.level} • 💰 ${r.u.coins}`);}
  if(["revelar_gartic","revelar_animal","revelar_enigma","revelar_anagrama","resetv","pular","responder","confirmar","participar","start_vord","help_vord","regras_vord","status_vord","rm_vord","add_vord","exit_vord","reset_vord","pontos","checkpts","rankpts"].includes(n)){return ctx.reply(`🎲 *${n.toUpperCase()}* integrado ao Dragon Fun 2.0.\nUse *${ctx.prefix}menubn* para iniciar uma rodada ou consultar os jogos disponíveis.`);}
  if(n==="casar"){if(!target||target===ctx.sender)return ctx.reply(`💍 Marque alguém: *${ctx.prefix}casar @user*`);const r=proposeMarriage(ctx.sender,target);return r.ok?ctx.conn.sendMessage(ctx.from,{text:`💍 ${tag(displaySender)} pediu ${tag(displayTarget)} em casamento!\n${tag(displayTarget)}, use *${ctx.prefix}aceitarcasamento* para aceitar.`,mentions:[displaySender,displayTarget]},{quoted:ctx.info}):ctx.reply("💔 Uma das pessoas já está em um relacionamento.");}
  if(["aceitarcasamento","aceitarpedido"].includes(n)){const r=acceptMarriage(ctx.sender);if(r.ok){const partner=await displayJid(ctx,r.partner);return ctx.conn.sendMessage(ctx.from,{text:`💒 ${tag(displaySender)} e ${tag(partner)} agora são um casal!`,mentions:[displaySender,partner]},{quoted:ctx.info});}return ctx.reply("Não existe pedido de casamento pendente para você.");}
  if(n==="divorciar"){const r=divorce(ctx.sender);if(r.ok){const partner=await displayJid(ctx,r.partner);return ctx.conn.sendMessage(ctx.from,{text:`💔 ${tag(displaySender)} e ${tag(partner)} se divorciaram.`,mentions:[displaySender,partner]},{quoted:ctx.info});}return ctx.reply("Você não está casado(a).");}
  if(["minhadupla","relacionamento","casais"].includes(n)){const p=marriageOf(ctx.sender);if(p){const partner=await displayJid(ctx,p);return ctx.conn.sendMessage(ctx.from,{text:`💞 Sua dupla é ${tag(partner)}.`,mentions:[partner]},{quoted:ctx.info});}return ctx.reply("💔 Você ainda não tem uma dupla.");}
  if(n==="familia"||n==="arvore"){const f=getFamily(ctx.sender);return ctx.conn.sendMessage(ctx.from,{text:`👨‍👩‍👧‍👦 *FAMÍLIA*\nFilhos: ${f.children.length?f.children.map(tag).join(", "):"nenhum"}`,mentions:f.children},{quoted:ctx.info});}
  if(["adotaruser","adotarfilho"].includes(n)){if(!target||target===ctx.sender)return ctx.reply("Marque alguém para adotar.");const f=familyAction(ctx.sender,target,"adopt");return ctx.conn.sendMessage(ctx.from,{text:`🍼 ${tag(displayTarget)} entrou na família de ${tag(displaySender)}!`,mentions:[displaySender,displayTarget]},{quoted:ctx.info});}
  if(n==="deserdar"){if(!target||target===ctx.sender)return ctx.reply("Marque quem deseja remover da família.");familyAction(ctx.sender,target,"remove");return ctx.conn.sendMessage(ctx.from,{text:`👋 ${tag(displayTarget)} foi removido(a) da família.`,mentions:[displayTarget]},{quoted:ctx.info});}
  if(["shipo","casal"].includes(n)){if(!target||target===ctx.sender)return ctx.reply("Marque alguém para shippar.");const v=stablePercent(`${ctx.sender}:${target}`,"ship");return ctx.conn.sendMessage(ctx.from,{text:`💘 *SHIPÔMETRO*\n${tag(displaySender)} ❤️ ${tag(displayTarget)}\nCompatibilidade: *${v}%*`,mentions:[displaySender,displayTarget]},{quoted:ctx.info});}
  if(["sn","chance"].includes(n)){return ctx.reply(`🔮 Chance: *${Math.floor(Math.random()*101)}%*`);}
  return ctx.reply(menu(ctx.prefix));
}
